Feature/add sidebar
nedradigital/ui-kit pull request #11
Opened 2020-09-22 11:13 UTC by karpovfv-nedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-22 14:38 UTC, nedradigital requested changes

2020-09-22 14:38 UTC, nedradigital commented on src/components/Sidebar/Sidebar.css
> +        border-radius: var(--control-radius) 0 0 var(--control-radius);
точно нужен бордер радиус по макетам?

2020-09-22 14:38 UTC, nedradigital commented on src/components/Sidebar/Sidebar.css
> +      transition: opacity 0.2s ease;
давай на "выезжание" заменим

2020-09-22 14:38 UTC, nedradigital commented on src/components/Sidebar/Sidebar.tsx
> +  useClickOutside({
Почему это кстати на клик аутсайд, а не на клик по оверлэю?

2020-09-22 14:38 UTC, nedradigital commented on src/components/Sidebar/Sidebar.tsx
> +const sidebarPropPosition = ['right', 'left'] as const;
,top, bottom

2020-09-23 10:08 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.tsx
> +const sidebarPropPosition = ['right', 'left'] as const;
добавил

2020-09-23 10:09 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.tsx
> +  useClickOutside({
использовал готовый хук, и в модалке тоже

2020-09-23 10:10 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +      transition: opacity 0.2s ease;
изменил. теперь фон плавно появляется и исчезает, сайдбар выезжает из-за границы экрана

2020-09-23 10:10 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +        border-radius: var(--control-radius) 0 0 var(--control-radius);
в макетах да, есть бордер радиус

2020-09-23 11:55 UTC, nedradigital requested changes

2020-09-23 11:55 UTC, nedradigital commented on src/components/Sidebar/Sidebar.css
> +        min-height: 200px;
давай в переменные сунем локальные

2020-09-23 11:55 UTC, nedradigital commented on src/components/Sidebar/Sidebar.tsx
> +  useClickOutside({
так зачем хук то?) почему не онклик по оверлэю, усложнение ведь

2020-09-23 11:55 UTC, nedradigital commented on src/components/Sidebar/Sidebar.css
> +          }
```
&-Window {
          &_position {
             &_right, &_bottom, &_left, &_right {
                transform: translate(0, 0);
            }
          }
}
```

2020-09-23 13:58 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +          }
спасибо

2020-09-23 13:58 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +        min-height: 200px;
сделано

2020-09-23 13:59 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.tsx
> +  useClickOutside({
убрал хук, добавил обычный онклик

2020-09-23 14:07 UTC, nedradigital approved these changes

2020-09-23 14:08 UTC, merged