Feat/consta 23
nedradigital/ui-kit pull request #21
Opened 2020-12-14 12:57 UTC by dmitriykorsakovnedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-14 13:29 UTC, karpovfv-nedra requested changes

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +  title: 'Components|/Breadcrumbs',
поменяй плиз `Components` на `Компоненты`

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +type Breadcrumbs = (props: Props) => React.ReactElement | null;
я думаю тут можно добавить всё из HTMLDivElement через `PropsWithHTMLAttributesAndRef<Props, HTMLDivElement>`

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export const Breadcrumbs: Breadcrumbs = (props) => {
и React.forwardRef

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
> +const testId = 'avatar';
может лучше breadcrumb'ом назвать?)

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +const cnButtonStories = cn('BreadcrumbsStories');
`cnBreadcrumbsStories`

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +    <div className={cnButtonStories()}>
ну и тут тоже `cnBreadcrumbsStories()`

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +import { Avatar } from '@consta/uikit/Breadcrumbs';
{ Breadcrumbs }

2020-12-14 13:29 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +  icon: React.FC<IconProps>;
тут лучше указать, что icon необязательный

2020-12-14 14:30 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +  title: 'Components|/Breadcrumbs',
+

2020-12-14 14:30 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export const Breadcrumbs: Breadcrumbs = (props) => {
done

2020-12-14 14:30 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +type Breadcrumbs = (props: Props) => React.ReactElement | null;
done

2020-12-14 14:30 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +    <div className={cnButtonStories()}>
done

2020-12-14 14:31 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
> +const testId = 'avatar';
done

2020-12-14 14:31 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +import { Avatar } from '@consta/uikit/Breadcrumbs';
done

2020-12-14 14:31 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx
> +const cnButtonStories = cn('BreadcrumbsStories');
done

2020-12-14 14:35 UTC, karpovfv-nedra approved these changes

2020-12-14 18:54 UTC, VladislavYukhimenko commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                  <span className={cnBreadcrumbs('Label')}>{page.label}</span>
а что если label сделать как ReactNode, и пусть сюда пробрасывают хоть текст, хоть иконку, хоть текст с иконкой?

2020-12-14 18:54 UTC, VladislavYukhimenko commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {pages.map((page, i) => {
https://codesandbox.io/s/kroshki-f3ei9

Давай так =)

2020-12-15 14:39 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {pages.map((page, i) => {
done

2020-12-15 14:39 UTC, merged